### ISSUE TITLE
No publication on packagist

### ISSUE THREAD

**Issue by Vincentv92** [pwnlabs/nusoap#52]
Hi there,

Thanks a lot for merging #51 but now I run into the issue that it's not published on packagist for some reason.
I believe this has to do with some webhooks not running to packagist or requires a manual trigger. 

If you need help with this, please let me know so I can help out with this

**Comment by f3l1x** [comment]
Hi, could you test it now?

**Comment by Vincentv92** [comment]
Awesome that worked!
