### ISSUE TITLE
call() function throws warning

### ISSUE THREAD

**Issue by L3RAZ** [pwnlabs/nusoap#59]
![image](https://user-images.githubusercontent.com/25088641/87413177-9f060f80-c5d2-11ea-853e-1620e943fbbf.png)
This error is thrown when nusoap function call is called. Since $params is an array and it is passed to varDump function after trying to use the parameter in strip_tags function it breaks.
`        $this->debug("call: operation=$operation, namespace=$namespace, soapAction=$soapAction, rpcParams=$rpcParams, style=$style, use=$use, endpointType=$this->endpointType");
        $this->appendDebug('params=' . $this->varDump($params));
        $this->appendDebug('headers=' . $this->varDump($headers));`

`function varDump($data)
    {
        ob_start();
        var_dump($this->sanitize($data));
        $ret_val = ob_get_contents();
        ob_end_clean();
        return $ret_val;
    }
    
    function sanitize($value) {
        return htmlspecialchars(strip_tags($value), ENT_COMPAT, 'utf-8');
    }`

**Comment by f3l1x** [comment]
Hi. Thanks. Do you try latest version or previous versions?

**Comment by L3RAZ** [comment]
Hello, this started happening with the latest version.

**Comment by DRoet** [comment]
Also seeing this after the v0.9.9 release

**Comment by IMSoP** [comment]
This is another bug introduced by PR #58

**Comment by f3l1x** [comment]
Because PR #58 seems buggy, I revert it and bump v0.9.10 (https://github.com/pwnlabs/nusoap/releases/tag/v0.9.10).

We need to dig deeper. Sorry for inconveniences.
