### ISSUE TITLE
Inifinite recursion in `nusoap_base->varDump`

### ISSUE THREAD

**Issue by IMSoP** [pwnlabs/nusoap#60]
PR #58 introduced a call to `sanitise` inside `varDump` here: https://github.com/pwnlabs/nusoap/pull/58/commits/4215f54c3311e44e44f34d82656c2520aee57862#diff-848ba0c3b184cd1507cdf73646ee4e30

This is incorrect, because `sanitise` expects a string, but `varDump` allows arrays and objects. If given another object extending from `nusoap_base`, this results in an infinite recursion, because `sanitise` will trigger a call to `__toString`, which calls `varDump` again.

`sanitise` should either be called on the _return value_ at the end of this function, or, preferably, only called when the data is actually being output (escaping should always be based on _output_ context).

Sample backtrace:

```
#238 strip_tags() called at [vendor/econea/nusoap/src/nusoap.php:919]
#239 nusoap_base->sanitize() called at [vendor/econea/nusoap/src/nusoap.php:912]
#240 nusoap_base->varDump() called at [vendor/econea/nusoap/src/nusoap.php:930]
#241 nusoap_base->__toString()
#242 strip_tags() called at [vendor/econea/nusoap/src/nusoap.php:919]
#243 nusoap_base->sanitize() called at [vendor/econea/nusoap/src/nusoap.php:912]
#244 nusoap_base->varDump() called at [vendor/econea/nusoap/src/nusoap.php:930]
#245 nusoap_base->__toString()
#246 strip_tags() called at [vendor/econea/nusoap/src/nusoap.php:919]
#247 nusoap_base->sanitize() called at [vendor/econea/nusoap/src/nusoap.php:912]
#248 nusoap_base->varDump() called at [vendor/econea/nusoap/src/nusoap.php:4205]
#249 nusoap_server->invoke_method() called at [vendor/econea/nusoap/src/nusoap.php:3843]
```

**Comment by f3l1x** [comment]
I see, thanks.

**Comment by IMSoP** [comment]
Reading through that PR, I can see multiple serious issues. The library is unusable to me without reverting that PR.

**Comment by f3l1x** [comment]
I reverted it as you suggested and bumped v0.9.10.
