### ISSUE TITLE
nuSoap PHP 7.2 gives Deprecated error on OpenCart

### ISSUE THREAD

**Issue by irmabbas** [pwnlabs/nusoap#65]
I used PHP 5.6 for a long time and after I change it to PHP 7.2 I get this error

[Sat Aug 22 23:23:02.457412 2020] [proxy_fcgi:error] [pid ****:tid ****] [client ****] AH01071: Got error 'PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_base has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 85\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_fault has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 1007\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_xmlschema has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 1095\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; soapval has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 2067\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; soap_transport_http has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 2169\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_server has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 3474\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; wsdl has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 4597\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_parser has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 6532\nPHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; nusoap_client has a deprecated constructor in /home/site/domains/mysite.com/public_html/system/library/nuSoap/nusoap.php on line 7183\n'

I use OpenCart 3.0.2.0
Will replacing this nuSoap file with my own fix my problem?

Thanks

**Comment by f3l1x** [comment]
Hi @irmabbas. It looks like it could help. Please test it and let us know.

**Comment by irmabbas** [comment]
> Hi @irmabbas. It looks like it could help. Please test it and let us know.

Hi, dear @f3l1x I change the file on a copy of my site on the localhost and the error is not visible anymore.
I will try it on the main site as soon as I get confirmation of two developers for PHP 7 compatibility and let you all know.
Thank you

**Comment by irmabbas** [comment]
Hi dear @f3l1x I just check it on my main site and It works fine I get no errors in my error logs
